### PR TITLE
more data

### PR DESCRIPTION
**Pull request by Emilgardis**
I'm not good at C#, but I think I managed to squeeze something out.

### CODE REVIEW

**Comment by Emilgardis** [comment]
~~Ok, not sure what's happening with the line endings... not able to fix it at all....~~

had to reapply the patches to make it not remember the random line ending change, why git why....

**Review by Ryex — APPROVED** [review]
These look good

**Comment by Ryex** [comment]
goo to merge?

**Comment by Emilgardis** [comment]
go ahead!

**Pull request merged**
